<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Defensive data cleanup: 2026_07_28_120000 dropped the Implementation
 * Request/Subscription tables and their ActivityType cases, but any
 * lead_activities rows already logged with activity_type =
 * 'implementation_request' / 'subscription_update' (system-generated by
 * the now-deleted ImplementationRequestService/SubscriptionService) would
 * still hard-fail Eloquent's enum cast with a ValueError on read, since
 * those cases no longer exist. No such rows existed in the live database
 * as of this migration, but this guards against any restored backup (or
 * other out-of-band data) predating the removal from ever reintroducing
 * the crash — mirrors the exact scenario/fix precedent of
 * 2026_07_24_090000_fix_implementation_requests_status_default.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::table('lead_activities')
            ->whereIn('activity_type', ['implementation_request', 'subscription_update'])
            ->delete();
    }

    public function down(): void
    {
        // Deleted rows described records (Implementation Requests/
        // Subscriptions) whose own tables are gone — nothing to restore.
    }
};
